apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: ticketing
build:
  local:
    push: false
  artifacts:
  - image: sandiprg/auth
    context: auth
    docker:
      dockerfile: Dockerfile
  - image: sandiprg/tickets
    context: tickets
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - ./infra/k8s/*
